name: Android CI

on:
  push:
    branches: [ "feature/setup-github-actions" ]
  pull_request:
    branches: [ "feature/setup-github-actions" ]

jobs:

  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setting up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant permission to gradlew file
        run: chmod +x gradlew

      - name: Building project
        run: ./gradlew build

      - name: Executing Lint
        run: ./gradlew lint

      - name: Executing Unit Test
        run: ./gradlew testDebugUnitTest

      - name: Executing Android Test
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          script: ./gradlew connectedAndroidTest

