name: Run test on pull request

# This action will be executed on every pull request to master or develop branch
on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  # We will user MacOS environment to build and execute our app test
  build:
    runs-on: macos-latest

    steps:
      # Checkout to our branch
      - uses: actions/checkout@v3

      # Setup Java Development Kit 21
      - name: Setting up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      # Load Google Services file
      - name: Load Google Services file
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}
        run: echo $DATA | base64 -D -o app/google-services.json

      - name: Create local.properties
        run: | 
          echo "tmdb_api_key=${{ secrets.TMDB_API_KEY }}" > local.properties

      # Grant access to gradlew file to execute commands
      - name: Grant permission to gradlew file
        run: chmod +x gradlew

      # Build project
      - name: Building project
        run: ./gradlew build

      # Execute lint
      - name: Executing Lint
        run: ./gradlew lint

      # Execute unit test
      - name: Executing Unit Test
        run: ./gradlew testDebugUnitTest :domain:testDebugUnitTest :data:testDebugUnitTest

      # Execute android test with the following configuration
      # - name: Executing Android Test
      #  uses: ReactiveCircus/android-emulator-runner@v2
      #  with:
      #    api-level: 30
      #    target: google_apis
      #    arch: x86_64
      #    script: ./gradlew connectedAndroidTest

